name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shader_graph:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/textures/
  shaders:
    - shaders/frame/IFrame Test.frag
    - shaders/mouse/IMouse Test.frag
    - shaders/mouse/Noise Lab (3D).frag
    # keyboard
    - shaders/keyboard/Keyboard Debug Overlay.frag
    - shaders/keyboard/Keyboard Test.frag
    # game
    - shaders/game_ported/Bricks Game.frag
    - shaders/game_ported/Bricks Game BufferA.frag
    - shaders/game_ported/Bricks Game BufferB.frag
    - shaders/game_ported/Pacman Game.frag
    - shaders/game_ported/Pacman Game BufferA.frag
    - shaders/game_ported/Pacman Game BufferB.frag
    # text
    - shaders/text/Text Texture.frag
    # multi-pass
    - shaders/multi_pass/MacOS Monterey wallpaper.frag
    - shaders/multi_pass/MacOS Monterey wallpaper BufferA.frag
    - shaders/multi_pass/Static Vec4 Grid A.frag
    # wrap & filter
    - shaders/wrap/Wrap Debug.frag
    - shaders/wrap/Black Hole ODE Geodesic Solver.frag
    - shaders/wrap/Broken Time Gate.frag
    - shaders/wrap/Goodbye Dream Clouds.frag
    - shaders/wrap/Tissue.frag
    - shaders/wrap/Transition Burning.frag
