name: shader_graph
description: "A multi-pass render-graph framework for Flutter runtime shaders (FragmentProgram/RuntimeEffect), with Shadertoy-style buffers and feedback."
version: 0.0.5
homepage: https://github.com/nightmare-space/shader_graph

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^5.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
